/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const useDialog: typeof import('~/composables/ui')['useDialog']
  const useLoadingBar: typeof import('~/composables/ui')['useLoadingBar']
  const useMessage: typeof import('~/composables/ui')['useMessage']
  const useNotification: typeof import('~/composables/ui')['useNotification']
}
